/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerVenda;
import Model.ModelProduto;
import java.util.LinkedList;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class ViewFormaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form ViewFormaPagamento
     */
    private String valorTotal;
    private LinkedList<ModelProduto> produtos;
    private ControllerVenda controllerVenda = new ControllerVenda();

    public ViewFormaPagamento() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public ViewFormaPagamento(String valorTotal, LinkedList<ModelProduto> produtos) {

        initComponents();

        this.produtos = new LinkedList<ModelProduto>(produtos);
        this.valorTotal = valorTotal;
        txtPrecoTotal.setText(this.valorTotal);

        txtPrecoFinal.setText(valorTotal);
        cbParcela.setEnabled(false);
        cbDesconto.setEnabled(true);
        txtPrecoTotal.setEnabled(false);
        txtPrecoFinal.setEnabled(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrecoTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbParcela = new javax.swing.JComboBox<>();
        txtPrecoFinal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnFinaliza = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbDesconto = new javax.swing.JComboBox<>();
        cbFormaPagamento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Escolha a forma de pagamento");

        jLabel1.setText("Preço total:");

        jLabel2.setText("Selecione a forma de pagamento:");

        cbParcela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x", "6x", "12x" }));
        cbParcela.setEnabled(false);

        jLabel3.setText("Preço final:");

        btnFinaliza.setText("Finalizar compra");
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Selecione um desconto:");

        cbDesconto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2%", "5%", "10%", "15%" }));
        cbDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDescontoActionPerformed(evt);
            }
        });

        cbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "Carnê" }));
        cbFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormaPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFinaliza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(txtPrecoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinaliza)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDescontoActionPerformed
        // TODO add your handling code here:

        if (cbDesconto.isEnabled()) {
            if (cbDesconto.getSelectedIndex() == 0) { //2, 5, 10 e 15
                System.out.println("mudou 2");
                txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal) * 0.98));
            } else if (cbDesconto.getSelectedIndex() == 1) { //2, 5, 10 e 15
                System.out.println("mudou 5");
                txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal) * 0.95));
            } else if (cbDesconto.getSelectedIndex() == 2) { //2, 5, 10 e 15
                System.out.println("mudou 10");
                txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal) * 0.9));
            } else if (cbDesconto.getSelectedIndex() == 3) { //2, 5, 10 e 15
                System.out.println("mudou 15");
                txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal) * 0.85));
            }
        }


    }//GEN-LAST:event_cbDescontoActionPerformed

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed
        controllerVenda.realizaVenda(produtos);
        JOptionPane.showMessageDialog(this, "Compra finalizada.");
        this.dispose();
    }//GEN-LAST:event_btnFinalizaActionPerformed

    private void cbFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormaPagamentoActionPerformed
        if (cbFormaPagamento.getSelectedIndex() == 0) {
            cbParcela.setEnabled(false);
            cbDesconto.setEnabled(true);
            if (cbDesconto.getSelectedIndex() == 0) { //2, 5, 10 e 15
                txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal) * 0.98));
            } else if (cbDesconto.getSelectedIndex() == 1) { //2, 5, 10 e 15
                txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal) * 0.95));
            } else if (cbDesconto.getSelectedIndex() == 2) { //2, 5, 10 e 15
                txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal) * 0.9));
            } else if (cbDesconto.getSelectedIndex() == 3) { //2, 5, 10 e 15
                txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal) * 0.85));
            }
        } else if (cbFormaPagamento.getSelectedIndex() == 1) {
            cbParcela.setEnabled(true);
            cbDesconto.setEnabled(false);
            txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal)));

        } else {
            txtPrecoFinal.setText(Double.toString(Double.parseDouble(valorTotal)));
            cbParcela.setEnabled(false);
            cbDesconto.setEnabled(false);
        }
    }//GEN-LAST:event_cbFormaPagamentoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFormaPagamento().setVisible(true);
            }
        });
    }

    public void setaValores() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JComboBox<String> cbDesconto;
    private javax.swing.JComboBox<String> cbFormaPagamento;
    private javax.swing.JComboBox<String> cbParcela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtPrecoFinal;
    private javax.swing.JTextField txtPrecoTotal;
    // End of variables declaration//GEN-END:variables
}
